spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop
    username: root
    password: fkquf9424
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED # Encountered deprecated setting 해결

      hibernate:
        default_batch_fetch_size: 100
        format_sql: true # ddl을 이쁘게 하려고 킴

    open-in-view: false
